### find all todos

GET http://localhost:8080/todos

###
GET http://localhost:8080/todos

// search by id: "http://localhost:8080/todos/5f8af701b836bf4fb3818b1a"

### save one todo

PUT http://localhost:8080/todos
Content-Type: application/json

{
  "name": "coca cola",
  "completed": false
}
