### find all todos

GET http://localhost:8080/todos

###
GET http://localhost:8080/todos

// search by id: "http://localhost:8080/todos/5f8af701b836bf4fb3818b1a"

### save one todo

PUT http://localhost:8080/todos
Content-Type: application/json

{
  "name": "coca cola",
  "completed": false
}


### Delete "list" of todos

DELETE http://localhost:8080/todos
Content-Type: application/json

[
  {
    "id": "5f8b648323f36641c4f8ae6f",
    "name": "aprender React",
    "complete": false,
    "dateTime": "2020-10-17T15:39:15.131"
  }
]


### borramos por id
DELETE http://localhost:8080/todos/5f8c66a64496e2000efd9991